### ISSUE TITLE
请问该怎么打开回国流量

### ISSUE THREAD

**Issue by yuwan027** [zxcvos/Xray-script#2]
打扰了 请问该怎么打开回国流量

**Comment by zxcvos** [comment]
~~建议看 Xray 文档~~ 去掉 `/usr/local/etc/xray/config.json` 配置中的
```jsonc
{
  "type": "field",
  "ip": [
    "geoip:cn"
  ],
  "outboundTag": "block"
},
```

**Comment by KevinMX** [comment]
https://xtls.github.io/document/level-2/warp.html

分流不当的情况下，也许配合 Warp 出站是更好的方法？
