### ISSUE TITLE
禁回国流量配置改进

### ISSUE THREAD

**Issue by THFX** [zxcvos/Xray-script#3]
建议在路由规则添加：

```json
      {
        "type": "field",
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "block"
      }
```

否则只靠 ip 会有漏网之鱼。
经实测，在 Win10 + Chrome 浏览器访问国内站点时，不添加上述配置无法实现屏蔽

**Comment by zxcvos** [comment]
[#2223](https://github.com/XTLS/Xray-core/issues/2223#issuecomment-1596699014) 

> chika0801: 建议不要用geosite cn阻止，如果你是用的加强版geo且你没细读它readme时。你可能会用了客户端遇到莫名现象

**Comment by zxcvos** [comment]
如果有需要，自行在 `/usr/local/etc/xray/config.json` 上添加
