### ISSUE TITLE
记录两个问题

### ISSUE THREAD

**Issue by mttydd** [zxcvos/Xray-script#5]

**Comment by mttydd** [comment]
1.在oracle linux安装lsb失败
需要手动安装：yum install redhat-lsb -y
删除原始脚本中安装lsb-release的语句

2.提示xray: command not found
编辑环境变量添加：/usr/local/bin

**Comment by zxcvos** [comment]
去除 lsb-release 安装，添加了 PATH
```shell
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin:/snap/bin
export PATH
```
