### ISSUE TITLE
关于网络优化的问题

### ISSUE THREAD

**Issue by Mabbs** [zxcvos/Xray-script#6]
有点好奇为什么网络优化的配置中会禁ping和禁ipv6

**Comment by zxcvos** [comment]
禁ping和禁ipv6是因为是直接 cv 萌咖大佬的 sysctl 配置，我也没用 ipv6，也就没怎么注意了。

**Comment by zxcvos** [comment]
:D 这些优化我都是直接 cv，现在 cv 一套新的优化，你可以再看看。
